version: "3"
services:
  postgres:
    image: kartoza/postgis:11.5-2.5
    volumes:
      - postgis-data:/var/lib/postgresql
      - dbbackups:/backups
    environment:
      # If you need to create multiple databases you can add coma separated databases, e.g., gis,data
      - POSTGRES_DB=db1
      - POSTGRES_USER=user1
      - POSTGRES_PASS=pass1
      - ALLOW_IP_RANGE=0.0.0.0/0
      # Add extensions you need to be enabled by default in the DB. Default are the specified below
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis

  qgis:
    build:
      context: ..
      dockerfile: ./.docker/Dockerfile
      args:
        QGIS_TEST_VERSION: ${QGIS_TEST_VERSION}
    tty: true
    volumes:
      - ${GITHUB_WORKSPACE}:/usr/src
    depends_on:
      - postgres
    links:
      - postgres
    command: ["/usr/src/run-docker-tests.sh"]
volumes:
  postgis-data:
  dbbackups:
